#ifndef _OPPW4_HASHES_SCREEN_H
#define _OPPW4_HASHES_SCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

char* additional_fn_screen(){
            return (char*)"; ScreenLayout\r\n"
                                    "0x09f5b4ee,doa_closet_terms.g1t\r\n"
                                    "0xace68753,doa_closet_terms.kscl\r\n"
                                    "0xbad39d23,doa_closet_terms.texinfo\r\n"
                                    "0x603b662b,external_banner_External_01.g1t\r\n"
                                    "0x283467e0,external_banner_External_01.texinfo\r\n"
                                    "0xd47a9e8a,external_banner_External_02.g1t\r\n"
                                    "0x7f5258bf,external_banner_External_02.texinfo\r\n"
                                    "0x48b9d6e9,external_banner_External_03.g1t\r\n"
                                    "0xd670499e,external_banner_External_03.texinfo\r\n"
                                    "0xbcf90f48,external_banner_External_04.g1t\r\n"
                                    "0x2d8e3a7d,external_banner_External_04.texinfo\r\n"
                                    "0x313847a7,external_banner_External_05.g1t\r\n"
                                    "0x84ac2b5c,external_banner_External_05.texinfo\r\n"
                                    "0xa5778006,external_banner_External_06.g1t\r\n"
                                    "0xdbca1c3b,external_banner_External_06.texinfo\r\n"
                                    "0x19b6b865,external_banner_External_07.g1t\r\n"
                                    "0x32e80d1a,external_banner_External_07.texinfo\r\n"
                                    "0x8df5f0c4,external_banner_External_08.g1t\r\n"
                                    "0x8a05fdf9,external_banner_External_08.texinfo\r\n"
                                    "0x02352923,external_banner_External_09.g1t\r\n"
                                    "0xe123eed8,external_banner_External_09.texinfo\r\n"
                                    "0x52d4ed8d,external_banner_External_10.g1t\r\n"
                                    "0x9a176e42,external_banner_External_10.texinfo\r\n"
                                    "0x9de6f293,external_store.kscl\r\n"
                                    "0xf9abb703,external_store_External_00.g1t\r\n"
                                    "0xfce08cb8,external_store_External_00.texinfo\r\n"
                                    "\r\n"
                                    "; Some more\r\n"
                                    "0x77b10168,doa_closet_ticket_info.g1t\r\n"
                                    "0xf694ca19,doa_closet_ticket_info.kscl\r\n"
                                    "0x08c01c9d,doa_closet_ticket_info.texinfo\r\n"
                                    "0xfed5b1bd,doa_closet_ticket_info_External_00.g1t\r\n"
                                    "0x12ba9a72,doa_closet_ticket_info_External_00.texinfo\r\n"
                                    "0x0405747b,doa_closet_ticket_period.g1t\r\n"
                                    "0xf4ceb966,doa_closet_ticket_period.kscl\r\n"
                                    "0xa0aece30,doa_closet_ticket_period.texinfo\r\n"
                                    "0xbd63762f,doa_theater_replay_detail.g1t\r\n"
                                    "0x6730ee32,doa_theater_replay_detail.kscl\r\n"
                                    "0x930cd5e4,doa_theater_replay_detail.texinfo\r\n"
                                    "0x83e769ba,doa_theater_replay_detail_External_00.g1t\r\n"
                                    "0xc8060bef,doa_theater_replay_detail_External_00.texinfo\r\n"
                                    "0xb46abed7,home_banner_retail.g1t\r\n"
                                    "0x5112ba8a,home_banner_retail.kscl\r\n"
                                    "0xae6f8a8c,home_banner_retail.texinfo\r\n"
                                    "0xe6da9605,home_update_info.g1t\r\n"
                                    "0x6c9dc91c,home_update_info.kscl\r\n"
                                    "0xe9a41aba,home_update_info.texinfo\r\n"
                                    "0xe19fe61d,online_nat_type.g1t\r\n"
                                    "0xca827c04,online_nat_type.kscl\r\n"
                                    "0x62939ed2,online_nat_type.texinfo\r\n"
                                    "0x9367f62f,online_text_chat_base.g1t\r\n"
                                    "0x51bc6e32,online_text_chat_base.kscl\r\n"
                                    "0xd2d155e4,online_text_chat_base.texinfo\r\n"
                                    "0x22b19ace,online_text_chat_text.kscl\r\n"
                                    "0x21d99ca0,rank_match_disconnection.g1t\r\n"
                                    "0x917f95e1,rank_match_disconnection.kscl\r\n"
                                    "0xea385bd5,rank_match_disconnection.texinfo\r\n"
                                    "\r\n"
                                    "; Ktid\r\n"
                                    "0x41abee93,SLE_doa_closet_terms.ktid\r\n"
                                    "0xb14f5e59,SLE_doa_closet_ticket_info.ktid\r\n"
                                    "0x1736df26,SLE_doa_closet_ticket_period.ktid\r\n"
                                    "0x7099cdf2,SLE_doa_theater_replay_detail.ktid\r\n"
                                    "0x9a04b9d3,SLE_external_store.ktid\r\n"
                                    "0xc18dae4a,SLE_home_banner_retail.ktid\r\n"
                                    "0xeceb23dc,SLE_home_update_info.ktid\r\n"
                                    "0x91ec22c4,SLE_online_nat_type.ktid\r\n"
                                    "0x29654df2,SLE_online_text_chat_base.ktid\r\n"
                                    "0xec7acc8e,SLE_online_text_chat_text.ktid\r\n"
                                    "0xfedf0621,SLE_rank_match_disconnection.ktid\r\n"
                                    "\r\n"
                                    "; The remaining files\r\n"
                                    "0xb34c062b,SLE_doa_theater_shogo.ktid\r\n"
                                    "0x98db3e56,doa_theater_shogo.g1t\r\n"
                                    "0xfab22aeb,doa_theater_shogo.kscl\r\n"
                                    "0xdf86328b,doa_theater_shogo.texinfo\r\n"
                                    "0x70bfa63f,tournament_External_00.g1t\r\n"
                                    "0xddb27df4,tournament_External_00.texinfo\r\n";
}

#ifdef __cplusplus
};
#endif

#endif